site_name: Soraya Remaili
site_url: https://sorayarem.com
nav:
  - Home: index.md
  - Research: research.md
  - Projects: projects.md
  - Contact Me: contact.md
theme:
  name: material
  icon:
    logo: material/star
  font:
    text: Merriweather Sans
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: green
      accent: deep orange
  features:
    - navigation.footer

extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:sremaili@email.sc.edu
    
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

copyright: Copyright &copy; 2025 Soraya Remaili


